### ISSUE TITLE
My image isn't uploading

### ISSUE THREAD

**Issue by KnowledgeWanderer** [ebess/advanced-nova-media-library#85]
So this is the error I'm getting and even if it passes, it's trying to insert an empty string in the DB.

![snip](https://user-images.githubusercontent.com/40168248/58092377-984d5980-7bd4-11e9-9edf-08a941fe2548.PNG)

Used this in the Page Nova Resource:
```
Images::make('Header Image', 'header_image')
                        ->thumbnail('thumb') 
                        ->rules('required'), 
```
Page model:
```
use Spatie\MediaLibrary\Models\Media;
use Spatie\MediaLibrary\HasMedia\HasMedia;
use Spatie\MediaLibrary\HasMedia\HasMediaTrait;

class Page extends Model implements HasMedia
{

    use HasMediaTrait;

    public function registerMediaConversions(Media $media = null)
    {
        $this->addMediaConversion('thumb')
            ->width(130)
            ->height(130);
    }

    public function registerMediaCollections()
    {
        $this->addMediaCollection('header_image')->singleFile();
    }
}
```

What the hell is the issue? The migration:
```
Schema::create('pages', function (Blueprint $table) {
            $table->bigIncrements('id');
            $table->string('slug');
            $table->string('header_image');
            $table->string('title');
            $table->text('body');
            $table->timestamps();
        });
```

**Comment by ebess** [comment]
@KnowledgeWanderer Hi, which version of this package are you using?

**Comment by KnowledgeWanderer** [comment]
@ebess `"ebess/advanced-nova-media-library": "^2.6"`, in composer.json

**Comment by ebess** [comment]
What's inside composer.lock? Something like:
```
{
            "name": "ebess/advanced-nova-media-library",
            "version": "1.2.0",
```

**Comment by KnowledgeWanderer** [comment]
```
{
            "name": "ebess/advanced-nova-media-library",
            "version": "2.7.1",
            "source": {
                "type": "git",
                "url": "https://github.com/ebess/advanced-nova-media-library.git",
                "reference": "3881a71c1447b76af83ddf2f4fbe6cc87a836c86"
            },
            "dist": {
                "type": "zip",
                "url": "https://api.github.com/repos/ebess/advanced-nova-media-library/zipball/3881a71c1447b76af83ddf2f4fbe6cc87a836c86",
                "reference": "3881a71c1447b76af83ddf2f4fbe6cc87a836c86",
                "shasum": ""
            },
            "require": {
                "laravel/framework": "^5.6",
                "php": ">=7.1.0",
                "spatie/laravel-medialibrary": "^7.5"
            },
            "type": "library",
            "extra": {
                "laravel": {
                    "providers": [
                        "Ebess\\AdvancedNovaMediaLibrary\\AdvancedNovaMediaLibraryServiceProvider"
                    ]
                }
            },
            "autoload": {
                "psr-4": {
                    "Ebess\\AdvancedNovaMediaLibrary\\": "src/"
                }
            },
            "notification-url": "https://packagist.org/downloads/",
            "license": [
                "MIT"
            ],
            "description": "Laravel Nova tools for managing the Spatie media library.",
            "keywords": [
                "laravel",
                "nova"
            ],
            "time": "2019-05-15T16:01:18+00:00"
        }
```

**Comment by ebess** [comment]
That's a known validation which has been fixed in https://github.com/ebess/advanced-nova-media-library/releases/tag/2.7.2. Just update the package `composer update ebess/advanced-nova-media-library` should fix it.

**Comment by KnowledgeWanderer** [comment]
@ebess Sweet, that solved that issue, but now I'm back to another one. I'm getting this:
![1](https://user-images.githubusercontent.com/40168248/58096367-98058c00-7bdd-11e9-94f0-492c9d436e61.PNG)
![2](https://user-images.githubusercontent.com/40168248/58096374-99cf4f80-7bdd-11e9-8407-bb58c63bef3a.PNG)

The spelling should be correct, there must be an issue with the way I called something? But I don't really know what's wrong. Did I place something wrong inside the Page model?

**Comment by KnowledgeWanderer** [comment]
added 
```
/**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'header_image', 'title', 'body', 'slug'
    ];
``` to the Page model just in case, still not working, like header_image doesn't exist

**Comment by KnowledgeWanderer** [comment]
@ebess please open the issue since it's pointless to start another one
